### NA value counts

```{r, t_var_stats1, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

column_name_count <- paste0("{{var}}", "_count")
column_name_na_count <- paste0("{{var}}", "_na_count")
df_filtered <- {{df}} %>% filter(!!sym(column_name_count) > !!sym(column_name_na_count))
kbl_table(na_summary({{df}}, "{{var}}")) %>% kable_styling(font_size = 12)

```

### Descriptive statistics

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
min_var <- min(df_filtered %>% pull(paste0("{{var}}", "_min"))) %>% round(2)
max_var <- max(df_filtered %>% pull(paste0("{{var}}", "_max"))) %>% round(2)
mean_var <- mean(df_filtered %>% pull(paste0("{{var}}", "_mean"))) %>% round(2)
median_var <- median(df_filtered %>% pull(paste0("{{var}}", "_median"))) %>% round(2)
```

  - `Min`: `r min_var`
  - `Median`: `r median_var`
  - `Mean`: `r mean_var`
  - `Max`: `r max_var`

### Summary table of `r tolower("{{var_name}}")` by platform

```{r, t_var_stats2, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

summary_table_var1 <- var_summary_1(df_filtered, "{{var}}")
create_dt_summary_tab(summary_table_var1 %>% format_var_summary_1("{{var_label}}"),
                      cols=c('Min({{var_label}})', 'Median({{var_label}})',
                             'Mean({{var_label}})', 'Max({{var_label}})'))

```
